version: '3.3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb-agenda-tarefas
    environment:
    - MONGO_DATA_DIR=./data/db
    ports:
      - "${MONGODBPORT}:27017"
    volumes:
      - ./data/db:/data/db